#!/bin/bash

: ${VERSION:=latest}

VOLUME="/data"
DOCKER_IMAGE="raniemi/cfn-lint:${VERSION}"

volume_option="-v "$(pwd):$VOLUME""
if [[ ! -z "${SHARED_VOLUME}" ]]; then
  volume_option="--volumes-from ${SHARED_VOLUME}"
fi

set -eu

docker run --rm -t $(tty &>/dev/null && echo "-i") \
           ${volume_option} \
           -v ~/.aws:/root/.aws \
           -w $VOLUME \
           --entrypoint "cfn-lint" \
           $DOCKER_IMAGE "$@"
